language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
addons:
  apt:
    packages:
    - lrzip
# command to install dependencies
#install: "pip install -r requirements.txt"
# command to run tests
script:
  - time curl -o demo.log.lrz https://stockholmuniversity.box.com/shared/static/u30tyl64mvngrl6b2hlksu5tu2i0wq9u.lrz
  - time lrzip -cdk -o demo.log demo.log.lrz
  - time cat demo.log >/dev/null
  - time cat demo.log >/dev/null
  - time cat demo.log >/dev/null
