language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
addons:
  apt:
    packages:
    - lrzip
    - time
install: "make pre-test"
script:
  - whereis time
  - which time
  - $TIME_CMD curl -o demo.log.lrz -L https://stockholmuniversity.box.com/shared/static/u30tyl64mvngrl6b2hlksu5tu2i0wq9u.lrz
  - $TIME_CMD lrzip -cdk -o demo.log demo.log.lrz
  - $TIME_CMD cat demo.log >/dev/null
  - $TIME_CMD cat demo.log >/dev/null
  - $TIME_CMD cat demo.log >/dev/null
  - $TIME_CMD du -sh demo.log*
  - make test
